### ISSUE TITLE
Feature request to create new users

### ISSUE THREAD

**Issue by KedarSant** [siesgstarena/arena-issue-tracking#24]
Creating a post request for a new user in the API

**Comment by Swap76** [comment]
@KedarSant Thanks for your valuable contribution we working hard on delivering new features every week you can check those out at http://arena.siesgst.ac.in/api/docs#changelog

For the request made by you, we need to think a bit because giving access to creating a user is a multistep process. Give us some time we will get back to you soon till the time you can work on new API released this week

**Comment by Swap76** [comment]
@KedarSant We have given a thought about this the signup process contains many parts like collecting info, validation, email verification, etc. That's why we have decided not to give API for this but we are developing API for other many functionalities you can have a look at recent changes http://arena.siesgst.ac.in/api/docs#changelog
